### ISSUE TITLE
Syntax highlighting vanished in the 11-lsp branch?

### ISSUE THREAD

**Issue by g2boojum** [alpha2phi/neovim-for-beginner#16]
This series has been really helpful for me. Thank you very much.

One thing that is confusing me is that syntax highlighting seems to have vanished in the first LSP branch (11-lsp), and I haven't been able to work out what's changed. It does come back in 12-lsp2, if that helps any.

Thanks again,
Grant

**Comment by g2boojum** [comment]
For whatever it's worth, I do get syntax highlighting back if I disable coq.

**Comment by mengwangk** [comment]
Fixed this in this commit - [Fix coq.nvim](https://github.com/alpha2phi/neovim-for-beginner/commit/96917e510d02ec1df57665f17c16b38a8c40c98c)

**Comment by g2boojum** [comment]
Much appreciated. 

I just tested it on my machine. 

```bash
$ rm -rf ~/.config/nvim-beginner  # completely redundant, I now see
$ git clone https://github.com/alpha2phi/neovim-for-beginner.git
$ cd neovim-for-beginner
$ git checkout 11-lsp
$ . ./install.sh
$ nvb  # to load all of the plugins, treesitter stuff, etc
$ nvb lua/plugins.lua
```

Still missing syntax highlighting. LSP is clearly working, since I see "Undefined global 'vim'" warnings, since I'm still on the 11-lsp branch, and not 12-lsp2. Neovim version 0.6.1, for whatever that's worth (the default version for Fedora 35, I think).

![image](https://user-images.githubusercontent.com/675903/152825433-6550dfa8-e92e-410a-b7fb-eb0b6241621f.png)

Syntax highlighting does return in 12-lsp2, so it's hardly the end of the world, and I'm finding this series incredibly helpful! Many thanks.

Here's the corresponding screen shot from 12-lsp2, just for comparison:

![image](https://user-images.githubusercontent.com/675903/152827647-1a79ff34-28e9-4667-8f00-b353121a40a3.png)

**Comment by CRAG666** [comment]
I have the same problem with the main branch
